# specify a bunch of file paths to the programs used in the analysis
# use absolute paths. Less portable but more stable.
# you have to activate the conda enviroment that was generated
# (https://github.com/broadinstitute/gatk -> Python Dependencies)

### PATH TO sambamba
sambamba: /g/huber/users/hirschmueller/miniconda3/envs/utils/bin/sambamba

### PATH TO samtools
samtools: /g/huber/users/hirschmueller/miniconda3/envs/utils/bin/samtools

### PATH TO bcftools
bcftools: /g/huber/users/hirschmueller/miniconda3/envs/utils/bin/bcftools

### PATH TO GATK4
GATK: /g/huber/users/hirschmueller/software/gatk-4.2.0.0/gatk

### SPECIFY PATHS FOR VEP
vep: /g/huber/users/hirschmueller/software/ensembl-vep/vep
vep_cache: /g/huber/users/hirschmueller/software/ensembl-vep/vep-cache

# Specify path to the reference genome
# sequence dictionary must be in same directory (created with CreateSequenceDictionary)
reference: /g/huber/users/hirschmueller/germline_calling/inputs/Homo_sapiens_assembly19.fa
reference_dict: /g/huber/users/hirschmueller/germline_calling/inputs/Homo_sapiens_assembly19.dict

# Path to dbSNP file.
dbSNP: /g/huber/users/hirschmueller/germline_calling/inputs/dbsnp_138.b37.verified.vcf.gz

# PATH TO HIGH CONFIDENCE INDEL AND SNPS
hapmap: /g/huber/users/hirschmueller/germline_calling/inputs/hapmap_3.3.b37.verified.vcf.gz
omni: /g/huber/users/hirschmueller/germline_calling/inputs/1000G_omni2.5.b37.verified.vcf.gz
thousandG_phase1_snps_high_confidence: /g/huber/users/hirschmueller/germline_calling/inputs/1000G_phase1.snps.high_confidence.b37.verified.vcf.gz
mills_indels: /g/huber/users/hirschmueller/germline_calling/inputs/Mills_and_1000G_gold_standard.indels.b37.verified.vcf.gz
axiom_poly: /g/huber/users/hirschmueller/germline_calling/inputs/Axiom_Exome_Plus.genotypes.all_populations.poly.verified.vcf.gz

# WE SCATTER THE COMPUTATIONALLY EXPENSIVE HAPLOTYPECALLER OVER INTERVALS. THESE ARE CREATED USING
# GATK SplitIntervals, i.e. like this:

# gatk SplitIntervals -R Homo_sapiens_assembly19.fa --scatter-count 25 -O WGS-interval-files-excluding-supercontigs
# -XL consensusBlacklist_ENCODE_hg19.bed -XL MT -XL GL000207.1 -XL GL000226.1 -XL GL000229.1 -XL GL000231.1
# -XL GL000210.1 -XL GL000239.1 -XL GL000235.1 -XL GL000201.1 -XL  GL000247.1  -XL GL000245.1 -XL  GL000197.1
# -XL GL000203.1 -XL  GL000246.1  -XL GL000249.1 -XL  GL000196.1 -XL GL000248.1 -XL GL000244.1 -XL GL000238.1
# -XL GL000202.1 -XL  GL000234.1 -XL GL000206.1 -XL GL000232.1 -XL GL000240.1 -XL GL000236.1 -XL GL000241.1
# -XL GL000243.1 -XL GL000242.1 -XL  GL000230.1 -XL GL000237.1 -XL  GL000233.1 -XL GL000204.1 -XL GL000198.1
# -XL GL000208.1 -XL GL000191.1 -XL GL000227.1 -XL GL000228.1 -XL GL000214.1 -XL GL000221.1 -XL GL000209.1
# -XL GL000218.1 -XL  GL000220.1 -XL GL000213.1 -XL GL000211.1 -XL GL000199.1 -XL  GL000217.1 -XL  GL000216.1
# -XL GL000215.1 -XL GL000205.1 -XL GL000219.1 -XL GL000224.1 -XL GL000223.1 -XL  GL000195.1 -XL   GL000212.1
# -XL GL000222.1 -XL GL000200.1 -XL GL000193.1 -XL GL000194.1 -XL  GL000225.1 -XL  GL000192.1 -XL NC_007605

# this creates a directory with the different intervals. Afterwards create a file which contains the paths to the
# individual intervals, i.e. with `readlink -f WGS-interval-files-excluding-supercontigs/* > intervals.txt`
intervals: /g/huber/users/hirschmueller/germline_calling/inputs/WGS-interval-files-excluding-supercontigs/intervals.txt

# PATH TO FILE WHICH CONTAINS ALL USED CHROMOSOMES (WE ONLY INCLUDE AUTOSOMES AND SEX CHROMOSOMES)
chromosomes: /g/huber/users/hirschmueller/germline_calling/inputs/chromosomes.txt

### INPUT
### PATH TO THE DIRECTORY WHERE THE SNAKEFILE IS. INSIDE THAT DIRECTORY ALL RESULTS WILL BE CREATED
path: /g/huber/users/hirschmueller/germline_calling/UPDATED-PIPELINE

### PATH TO DIRECTORY IN WHICH TEMPORARILY FILES SHOULD BE CREATED. THIS DIRECTORY HAS TO ALREADY EXIST!
tmp_dir: /scratch/hirschmu

# PATH TO THE DIRECTORY WHERE THE COHORT GVCF SHOULD BE CREATED
cohort_dir: /g/huber/users/hirschmueller/germline_calling/UPDATED-PIPELINE/cohort

# PATH TO FILE WHICH WILL CONTAIN ALL THE SAMPLE NAMES USED IN THE BAM FILE. THIS FILE GETS CREATED AUTOMATICALLY AND IS
# USEFUL FOR SUBSETTING A SPECIFIC PATIENT LATER.
bam_sample_names: /g/huber/users/hirschmueller/germline_calling/UPDATED-PIPELINE/bam_sample_names.txt

# Actual input files.
# This workflow starts of we BAM files where duplicates are already marked (i.e. with sambamba markdup)

# specify a patient identifier and as well as the corresponding BAM file. The order MUST match, i.e.
# first patient ID should match the first BAM file. Bam files have to be indexed, i.e. with samtools index

patient_id:
  - H005-00ML

bam_files:
  - /g/huber/projects/nct/cll/ProcessedData/WGS/BAM/control/control_H005-00ML_merged.mdup.bam